version: '{build}'

environment:
  irrklang_pro:
    secure: IHiumvV9+f+4JOGb9Al3Husl+Hox2gCq90R74mJQy+g=
  AUTH_TOKEN:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO

install:
  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip ; exit 0"
  - 7z x premake-5.0.0-alpha12-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz ; exit 0"
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/freetype/freetype-2.8.1.tar.bz2 ; exit 0"
  - tar xf freetype-2.8.1.tar.bz2
  - move freetype-2.8.1 freetype
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip ; exit 0"
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.3.4.tar.gz ; exit 0"
  - tar xf lua-5.3.4.tar.gz
  - move lua-5.3.4\src lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2017/sqlite-amalgamation-3210000.zip ; exit 0"
  - 7z x sqlite-amalgamation-3210000.zip
  - move sqlite-amalgamation-3210000 sqlite3
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name http://www.ambiera.at/downloads/irrKlang-32bit-1.5.0.zip ; exit 0"
  - 7z x irrKlang-32bit-1.5.0.zip
  - move irrKlang-1.5.0 irrklang
  - move irrklang\plugins\ikpMP3 ikpmp3

  # let premake happy
  - cp -rf premake/* .

  #irrklang pro
  - 7z x -oirrklang/lib/Win32-visualStudio -p%irrklang_pro% -y irrklang/irrKlang.7z
  
  # patch irrlicht & ikpmp3
  - patch -p0 < irrlicht\irrlicht.patch
  - patch -p0 < ikpmp3\ikpmp3.patch

  # premake
  - premake5 vs2015
  
configuration: Release

build: 
    project: build/ygo.sln
    parallel: true

after_build:
  - mv -f bin/release/ygopro.exe ygopro_thc.exe
  
  - git config --global user.name "Smile-DK"
  - git config --global user.email "2236141431@qq.com"
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/HuangYuNan/thcsvr/archive/master.zip ; exit 0"
  - 7z x thcsvr-master.zip
  - mv -f thcsvr-master/expansions/pics .
  - mv -f thcsvr-master/expansions/script .
  - rm -rf cards.cdb
  - mv -f thcsvr-master/expansions/thc.cdb cards.cdb
  - mv -f thcsvr-master/expansions .

  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/shirone777/windbot/archive/master.zip ; exit 0"
  - 7z x windbot-master.zip
  - cd windbot-master
  - msbuild /property:Configuration=Release /property:Platform=x86
  - rm -rf bin/Release/WindBot.exe.config
  - mv -f bin/Release ../WindBot
  - mv -f BotWrapper/bin/Release/Bot.exe ./..
  - mv -f BotWrapper/bin/Release/Bot.conf ./..
  - cd ..
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/utility.lua ; exit 0"
  - mv -f utility.lua script
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/Fluorohydride/ygopro-scripts/raw/master/constant.lua ; exit 0"
  - mv -f constant.lua script

  - rm -rf pics/thumbnail pics/*.db expansions/pics/thumbnail expansions/pics/*.db
  - mkdir replay

  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/moecube/ygopro-starter-pack/archive/master.zip ; exit 0"
  - 7z x ygopro-starter-pack-master.zip
  - cp -rf ygopro-starter-pack-master/* .

  - 7z a -mx9 -xr!.git* ygopro-THC.7z ygopro_thc.exe lflist.conf expansions LICENSE README.md strings.conf system.conf cards.cdb script textures deck single pics replay WindBot Bot.exe bot.conf

test: off

artifacts:
  - path: ygopro_thc.exe
    name: ygopro client for thc
  - path: ygopro-THC.7z
    name: ygopro-THC

deploy:
  release: latest
  description: 'Automatic build commit $(APPVEYOR_REPO_COMMIT) $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  force_update: true
  auth_token:
    secure: EQ9miMjfX/QAoBvgc6D+JLmHatLyxOEKZ/uo68QijxWW5Gp4MzB/pOH9+u2GlDVO
  on:
    branch: koishibuild

cache:
  - premake-5.0.0-alpha12-windows.zip
  - libevent-2.0.22-stable.tar.gz
  - freetype-2.8.1.tar.bz2
  - irrlicht-1.8.4.zip
  - lua-5.3.4.tar.gz
  - sqlite-amalgamation-3210000.zip
  - irrKlang-32bit-1.5.0.zip
  - premake-5.0.0-alpha10-windows.zip
  - Redis-x64-3.2.100.zip
